[package]
name = "stocks"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0.66"
chrono = { version = "0.4.23", features = ["serde"] }
cli-table = "0.4.7"
reqwest = { version = "0.11.13", features = ["json"]}
serde = { version = "1.0.148", features = ["derive"] }
serde_json = "1.0.89"
tokio = { version = "1.22.0", features = ["macros", "rt-multi-thread"] }
