[package]
name = "stocks"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0.66"
chrono = { version = "0.4.23", features = ["serde"] }
cli-table = "0.4.7"
serde = { version = "1.0.148", features = ["derive"] }
serde_json = "1.0.89"
ureq ={ version = "2.6.2", features = ["json"] }
