[package]
name = "stocks"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.0.26", features = ["derive"] }
cli-table = "0.4.7"
env_logger = "0.9.3"
log = "0.4.14"
rayon = "1.5.3"
reqwest = { version = "0.11.12", features = ["json", "blocking"]}
serde = { version = "1.0.1", features = ["derive"] }
serde_json = "1.0.7"
tokio = { version = "1.22.0", features = ["full"] }
