[package]
name = "stocks"
version = "0.1.0"
edition = "2021"

[lib]
name = "stocks"
path = "src/lib.rs"

[[bin]]
name = "stocks"
path = "src/bin.rs"

[dependencies]
structopt = "0.3.25"
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.73"
reqwest = { version = "0.11.8", features = ["json", "blocking"]}
rayon = "1.5.1"
cli-table = "0.4.6"