[package]
name = "stocks"
version = "0.1.0"
edition = "2021"


[dependencies]
structopt = "0.3.26"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
reqwest = { version = "0.11.9", features = ["json", "blocking"]}
rayon = "1.5.1"
cli-table = "0.4.6"
env_logger = "0.9.0"
log = "0.4.14"
